from __future__ import annotations


V61_STRATEGIES = [
    "DADDY_VOLUME_NECKLINE",
    "ICT_FVG_OB_SWEEP",
    "COMBINED_VOLUME_ICT",
]

V61_SETUP_STRATEGIES = [
    "FVG_LIQUIDITY_SWEEP",
    "FVG_OB_OVERLAP",
    "SR_FLIP_RETEST_VOLUME",
    "FIB_PULLBACK_VOLUME",
    "PULLBACK_WICK_VOLUME",
]
