from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import Any

from scenario_telemetry.v688_common import (
    ACTIVE_ROUTE,
    RESEARCH_ROUTES,
    SHADOW_ROUTES,
    load_context,
    route_label,
    safe_status,
    write_html,
    write_json,
)


def build_scenario_genome(reports_dir: str | Path = "docs/reports") -> dict[str, Any]:
    ctx = load_context(reports_dir)
    backfill = ctx["backfill"]
    runtime = ctx["runtime"]
    display_primary = _display_primary(backfill)
    actual = backfill.get("active_route") or runtime.get("active_route") or ACTIVE_ROUTE
    forward_runner = runtime.get("active_route") or ACTIVE_ROUTE
    cards = [_card(ACTIVE_ROUTE, "ACTIVE")]
    cards.extend(_card(route, "SHADOW") for route in SHADOW_ROUTES)
    cards.extend(_card(route, "RESEARCH") for route in RESEARCH_ROUTES)
    route_state = {
        "display_primary_route": display_primary,
        "actual_paper_primary_route": actual,
        "forward_runner_route": forward_runner,
        "shadow_routes": SHADOW_ROUTES,
        "mismatch_warning": display_primary != actual or forward_runner != actual,
    }
    payload = {
        "schema_version": "v688_scenario_genome_v1",
        "cards": cards,
        "route_state": route_state,
        "scenario_count": len(cards),
        **safe_status(),
    }
    reports = Path(reports_dir)
    write_json(reports / "latest_v688_scenario_genome_summary.json", payload)
    write_html(
        reports / "latest_v688_scenario_genome_report.html",
        "V6.8.8 Scenario Genome",
        [("Route State", route_state), ("Scenario Cards", cards)],
    )
    return payload


def _display_primary(backfill: dict[str, Any]) -> str:
    routes = backfill.get("routes", [])
    if not routes:
        return backfill.get("active_route") or ACTIVE_ROUTE
    best = max(routes, key=lambda row: float(row.get("return_pct", -999.0) or -999.0), default={})
    return best.get("scenario") or backfill.get("active_route") or ACTIVE_ROUTE


def _card(scenario_id: str, status: str) -> dict[str, Any]:
    family = _family(scenario_id)
    return {
        "scenario_id": scenario_id,
        "display_name": route_label(scenario_id),
        "scenario_family": family,
        "status": status,
        "preferred_market_states": _preferred(scenario_id),
        "weak_market_states": _weak(scenario_id),
        "entry_style": _entry_style(scenario_id),
        "exit_style": "guarded_exit" if "GUARD" in scenario_id or "LG" in scenario_id else "standard_exit",
        "risk_style": "drawdown_sensitive" if "BEAR" in scenario_id or "LG" in scenario_id else "balanced",
        "sizing_style": "multiplier_cap" if "M3" in scenario_id else "fixed_paper_size",
        "core_variables": ["PF20", "monthly_return", "HWM_drawdown", "dominance_risk"],
        "tunable_params": _params(scenario_id),
        "hard_filters": ["LIVE_NOT_ALLOWED", "manual_review_required"],
        "soft_filters": ["market_state", "candidate_quality", "expected_rr"],
        "known_strengths": _strengths(scenario_id),
        "known_weaknesses": _weaknesses(scenario_id),
        "failure_signatures": ["candidate_starvation", "profit_giveback", "regime_mismatch"],
        "expected_behavior": "paper-only scenario telemetry subject; no active auto-change",
        "last_review_date": date.today().isoformat(),
        "manual_notes": "Generated by V6.8.8 engine; manual approval required for any change.",
    }


def _family(scenario_id: str) -> str:
    if "BEAR" in scenario_id:
        return "bear_defense"
    if "LG" in scenario_id or "LOSS" in scenario_id:
        return "loss_guard"
    if "ROLLING" in scenario_id:
        return "rolling"
    if "BALANCED" in scenario_id:
        return "balanced"
    if "ATR" in scenario_id:
        return "atr_research"
    return "research"


def _preferred(scenario_id: str) -> list[str]:
    if "BEAR" in scenario_id:
        return ["RISK_OFF_ALT_WEAK", "EDGE_DECAY"]
    if "ROLLING" in scenario_id:
        return ["BULL_ATTACK", "ALT_FRIENDLY"]
    if "BALANCED" in scenario_id:
        return ["NORMAL", "ALT_FRIENDLY"]
    return ["EDGE_DECAY", "RISK_OFF_ALT_WEAK"]


def _weak(scenario_id: str) -> list[str]:
    if "BEAR" in scenario_id:
        return ["BULL_ATTACK"]
    if "ROLLING" in scenario_id:
        return ["RISK_OFF_ALT_WEAK"]
    return ["HIGH_NOISE", "UNCLASSIFIED"]


def _entry_style(scenario_id: str) -> str:
    if "BEAR" in scenario_id:
        return "defensive_long_or_wait"
    if "ROLLING" in scenario_id:
        return "momentum_reinvestment"
    return "guarded_long"


def _params(scenario_id: str) -> dict[str, float]:
    if "M3" in scenario_id:
        return {"pf_threshold": 0.8, "monthly_loss_threshold": -3.0, "hwm_dd_threshold": -8.0}
    if "BEAR" in scenario_id:
        return {"bear_window_threshold": 1.0, "atr_guard": 1.0}
    return {"pf_threshold": 1.0, "hwm_dd_threshold": -10.0}


def _strengths(scenario_id: str) -> list[str]:
    if "BEAR" in scenario_id:
        return ["drawdown defense", "risk-off filtering"]
    if "ROLLING" in scenario_id:
        return ["capital growth in strong trend"]
    return ["balanced paper route", "dominance-aware guard"]


def _weaknesses(scenario_id: str) -> list[str]:
    if "BEAR" in scenario_id:
        return ["can miss upside rebounds"]
    if "ROLLING" in scenario_id:
        return ["drawdown expansion in weak regimes"]
    return ["candidate starvation possible", "MICRO_STATE_WEAK overblocking possible"]
